# Generated by Django 4.2.1 on 2023-05-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem_bot', '0002_stat_profile_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='date',
            field=models.TextField(unique=True, verbose_name='Дата'),
        ),
    ]
